name: waktu_solat_malaysia_mobile
description: A Flutter app for Malaysia prayer times, qibla compass, and tasbih.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  geolocator: ^13.0.2
  http: ^1.2.2
  intl: ^0.20.2
  flutter_compass: ^0.8.1
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  provider: ^6.1.2
  app_links: ^6.4.1
  home_widget: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
